### ISSUE TITLE
25$ Bounty | Local Development: Cloudflare Worker (HonoJS) Accessing R2 Files

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#125]
### Scenario:

Our backend is a cloudflare worker. It's a serverless architecture. Cloudflare also provides R2, an object store, like AWS S3, to manage file uploads. 

When we upload a file from production instance, the file gets uploaded to the R2 bucket successfully, and a key is generated.
To access this uploaded file, we can setup subdomains that facilitate a base-url that can be used for the file downloads. 

**file-path = subDomainUrl + key** 

> wrangler.toml file > R2_SUBDOMAIN_URL 

<hr />

### Here is the catch:

When we upload a file from dev mode (locally), the file gets uploaded to the local cache (within .wrangler/state/../R2/blob) instead of the R2 bucket.
Now, To access this uploaded file, we need a url.
Without the url, we cannot generate a file path.  
And without the filepath, we cannot access the file on the frontend.

<hr />

I'd like to find a solution that allows me (developer) to test my Worker's upload & download file functionality with Cloudflare R2 **during local development**. 

For example, from local dev instance, A user should be able to successfully upload their profile picture and should be able to access the profile picture as a url.

- Use CloudFlare R2 only

### Points to consider:
- frontend/src/config.ts > FF_IMAGE_UPLOADS = false - will disable the upload feature.
- wrangler.toml > The configuration file for Cloudfare wrangler
- backend/.wrangler > will contain uploaded file blobs when app is running using `npm run dev`

**Comment by aliraza556** [comment]
Hi @aadeshkulkarni, Could you please assign me?

**Comment by aliraza556** [comment]
@aadeshkulkarni, I have already set up the project. Could you please assign me the next task?

**Comment by darshanmodi13** [comment]
@aadeshkulkarni Can you please describe in detail the reproduction steps again?

**Comment by aadeshkulkarni** [comment]
@aliraza556 - Assigning it to you. As this is time-critical issue with a bounty, You will have 48 hours to come up with a solution. If you're unable to solve it by then, you will be unassigned automatically, so that someone else can pick it up.

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni Can you please describe in detail the reproduction steps again?

Step 1: Run the backend & frontend server locally.
Step 2: Ensure that you comment Production link for BACKEND_URL and uncomment the local link for BACKEND_URL in `frontend/src/config.ts` file
Step 3:  Spin up the frontend & backend using `npm run dev` in both frontend and backend folders.
Step 4: Open the app on localhost:5173 and Signup, signin.
Step 5: Go to Profile (from top right) > About > Update profile picture > Save

<img width="1761" alt="Screenshot 2024-06-03 at 11 41 15 PM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/f276e679-808a-4d89-9d49-da3bd6e71c68">


After saving, IDEALLY, you should be able to see the updated profile picture everywhere in the app.
But, that won't happen on Dev mode. 

The challenge is to make this Step 5 work locally using cloudflare R2.

**Comment by aliraza556** [comment]
> @aliraza556 - Assigning it to you. As this is time-critical issue with a bounty, You will have 48 hours to come up with a solution. If you're unable to solve it by then, you will be unassigned automatically, so that someone else can pick it up.

@aadeshkulkarni, Ok

**Comment by aliraza556** [comment]
Hi @aadeshkulkarni, I tried to set up the project locally, but I am facing an issue connecting to the database. Could you please help me with this?

`.env file`:

![image](https://github.com/aadeshkulkarni/medium-app/assets/87068339/0c2b0a18-50b2-4672-83cf-b7c71b24c5e5)

`wrangler.toml   file:`

![image](https://github.com/aadeshkulkarni/medium-app/assets/87068339/cd2a3007-845a-424f-8fd2-d709814791df)

`config.ts file:`

![image](https://github.com/aadeshkulkarni/medium-app/assets/87068339/c84ea389-c7f6-402d-88e6-f733a91fbace)

When I sign up, I get this error:

![image](https://github.com/aadeshkulkarni/medium-app/assets/87068339/60547f49-5173-4a24-918b-bef314b5e0a3)

**Comment by aadeshkulkarni** [comment]
@aliraza556  -  You will need to setup Prisma Connection string as well. Check the installation setups in readme.

**Comment by aliraza556** [comment]
Hi @aadeshkulkarni,
Please review it, I'm going to make a pull request (PR).

![image](https://github.com/aadeshkulkarni/medium-app/assets/87068339/fcc5d8ca-4b65-4da4-ab7b-2bc4411914ff)

**Comment by Ashutoshpadhi629** [comment]
hello @aadeshkulkarni , can you assign me to this issue?

**Comment by aadeshkulkarni** [comment]
Sure, here you go

**Comment by Ashutoshpadhi629** [comment]
@aadeshkulkarni 
# We need to run wrangler dev --remote for dev mode
<img width="703" alt="Screenshot 2024-07-04 at 2 23 06 AM" src="https://github.com/aadeshkulkarni/figuringout/assets/81710269/b6666864-8754-4432-8400-f6806054d61c">
docs link :
[https://developers.cloudflare.com/r2/api/workers/workers-api-usage/#4-access-your-r2-bucket-from-your-worker](url)

# to perform against a real R2 bucket in dev mode 
<img width="392" alt="Screenshot 2024-07-04 at 2 34 58 AM" src="https://github.com/aadeshkulkarni/figuringout/assets/81710269/321b95cd-edec-46c0-acb4-ea4a43425c6c">

# also we need a different Bucket for local development
<img width="709" alt="Screenshot 2024-07-04 at 2 23 16 AM" src="https://github.com/aadeshkulkarni/figuringout/assets/81710269/e6a31f35-a894-4cb6-88e5-dad9105d376b">

wrangler.toml
<img width="402" alt="Screenshot 2024-07-04 at 2 35 10 AM" src="https://github.com/aadeshkulkarni/figuringout/assets/81710269/52643ee8-0ae0-41be-af29-0ba46ba2f58b">

**Comment by Ashutoshpadhi629** [comment]
should i continue with this approach @aadeshkulkarni ?

**Comment by aadeshkulkarni** [comment]
Sure, please go ahead
