### ISSUE TITLE
Feature | Landing page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#134]
Using this portfolio video as a reference point, build a landing page for our app - Figuringout.life 

Reference: https://youtu.be/FTH6Dn3AyIQ?si=2sxai20i67MjHIax

For now, add the page as a new route `/landing`

Once done, share a PR and attach a video recording of your output.

**Comment by bruno-corso** [comment]
Hey, I got a doubt... the Landing Page is going to be a hook for news users or for dev helping on the project?

**Comment by aadeshkulkarni** [comment]
New users

**Comment by aadeshkulkarni** [comment]
This has been open for a long time. If no one else picks it by the weekend, I'll pick it up
