### ISSUE TITLE
Bug | Profile > About | Responsiveness

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#145]
The text in the upload picture section goes outside the screen width. It should be responsive.

### Screenshot

![Screenshot 2024-06-07 at 3 13 23 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/4611aff1-5e69-4a3b-b4c9-19d47a83b64f)

**Comment by parthzile** [comment]
**Proposed Solution**
CSS Adjustments:

> Use media queries to adjust the font size and layout for smaller screens.
> Ensure the container of the text has appropriate padding and margins.
> Implement word wrapping to ensure long text does not overflow.

 Responsive Design Implementation:

> Modify the CSS to use flexible units (like percentages or viewport units) instead of fixed units (like pixels).
> Adjust the flexbox/grid properties to ensure elements resize and rearrange appropriately.

Testing:

> Test the changes on various screen sizes using browser developer tools.
> Ensure that the text is readable and the layout is visually appealing on both mobile and desktop devices.

**Comment by aadeshkulkarni** [comment]
Sounds good.

**Comment by parthzile** [comment]
Sure then, will start working on the issue!

**Comment by aadeshkulkarni** [comment]
@parthzile - Please share an update on the issue every 24 - 48 hours. Otherwise, the issue will be unassigned.

**Comment by aakashsharma7** [comment]
@aadeshkulkarni kindly assign this issue to me

**Comment by aadeshkulkarni** [comment]
Sure, assigned it to you.

**Comment by Shashan17J** [comment]
@aadeshkulkarni Please Review.
