### ISSUE TITLE
Feature | Dark / Light mode

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#150]
Setup Dark & Light mode for the app where light mode = currrent setup. 

The Color, typography, spacing, roundedness, etc. should be easily configurable from 1 config file.
Build using tailwind CSS.

Ensure that you're implementing modes in the most optimised, efficient manner.

### **DO NOT BREAK EXISTING FEATURES**

**Comment by vverma022** [comment]
I'd like to work on this feature. As the project is in tailwind I would try implementing it using the selector strategy.

**Comment by aadeshkulkarni** [comment]
Sure. only 1 issue can be assigned to a contributor at a time.

If no one claims the issue before you complete #146, will assign it to you.

**Comment by vverma022** [comment]
> Sure. only 1 issue can be assigned to a contributor at a time.
> 
> If no one claims the issue before you complete #146, will assign it to you.

Can you assign it

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by aadeshkulkarni** [comment]
@vverma022 - Please set the primary, secondary colors for both light and dark mode in tailwind.config.js And then use bg-primary / bg-secondary in the code.

This would be a much cleaner approach and will be easier to maintain in future

**Comment by Shashan17J** [comment]
Assign this task to me

**Comment by Shashan17J** [comment]
Assign this to me.

**Comment by aadeshkulkarni** [comment]
Share your approach first.

**Comment by Shashan17J** [comment]
1.Enable the 'darkMode' feature in the 'tailwind.config.js' file.
2. Create a component that toggles dark mode and save preference in localStorage.
3. Modify the logout function to preserve the dark mode preference.
4. And then style the UI Ex. dark:bg-white.

**Comment by aadeshkulkarni** [comment]
We are planning to integrate Shadcn soon. Can you implement dark modes using Shadcn ?

**Comment by vverma022** [comment]
> We are planning to integrate Shadcn soon. Can you implement dark modes using Shadcn ? I'll do it I have the code base already.

**Comment by vverma022** [comment]
If shadcn needs to be implemented then the implication will be easy as well as structuring the app-bar component. I'll make a new brach to solve this issue as the current one has its issues.

**Comment by Shashan17J** [comment]
I have already implemented dark mode; only a few things remain.
![Screenshot 2024-06-26 120153](https://github.com/aadeshkulkarni/figuringout/assets/130395029/d5e61b34-796c-4467-8a38-7e5ad8eecfb5)
![Screenshot 2024-06-26 115049](https://github.com/aadeshkulkarni/figuringout/assets/130395029/c7a028c9-0600-4032-a568-3e7be7c27853)
![Screenshot 2024-06-26 115105](https://github.com/aadeshkulkarni/figuringout/assets/130395029/a81acbc6-4eef-428f-b5fe-0dd836e30fb9)
![Screenshot 2024-06-26 115631](https://github.com/aadeshkulkarni/figuringout/assets/130395029/ab9947f7-685c-43a5-8d9a-f0badc47f72d)
![Screenshot 2024-06-26 115654](https://github.com/aadeshkulkarni/figuringout/assets/130395029/377a0725-fb49-4766-8806-d89b230bfd93)
![Screenshot 2024-06-26 115751](https://github.com/aadeshkulkarni/figuringout/assets/130395029/8516c869-408d-4a77-852d-7d6cfbae2fde)

**Comment by Shashan17J** [comment]
Every thing is responsive including AppBar Component

**Comment by Shashan17J** [comment]
@aadeshkulkarni if this is OK, then I can create a pull request for this issue.

**Comment by aadeshkulkarni** [comment]
@Shashan17J  - Is this done using shadcn ?

**Comment by Shashan17J** [comment]
@aadeshkulkarni without shadcn.

**Comment by aadeshkulkarni** [comment]
In that case, pause. 
@vverma022 - Can you build it using shadcn ? If yes, please share timelines.

**Comment by vverma022** [comment]
> In that case, pause. @vverma022 - Can you build it using shadcn ? If yes, please share timelines.

Probably yes, Shadcn already provides dark theme as well as the toggle component. I'll try and get to done by tomorrow. Any preferences or suggestions.

**Comment by aadeshkulkarni** [comment]
> > In that case, pause. @vverma022 - Can you build it using shadcn ? If yes, please share timelines.
> 
> Probably yes, Shadcn already provides dark theme as well as the toggle component. I'll try and get it done by tomorrow. Any preferences or suggestions ?

Yes.
- Use default theme, instead of New york. So that we can make use of lucide-react icons in future. 
- Try to ensure that all colors are configurable from one place (global.css or tailwind config)

Break the task down into steps.

Step 1: Try to setup shadcn first. And see everything works as is currently. (Light mode i mean)
Step 2: Add dark mode incrementally. One page at a time. Start with simple pages like Sign up, Sign in. Make sure you commit your code on each step with the appropriate commit messages. 
Step 3: Once all pages are done. Check components. 

Don't add any Shadcn components for now. (unless absolutely necessary). We will do it as a separate ticket.

Document everything that you achieved and also things that can be done later.

**Comment by vverma022** [comment]
As of now I have just added 2 components. A button and a dropdown which will act as the trigger's for the dark mode. So instead of using one of the default colour schemes implement it manually by changing and adding theme's in the index.css and tailwind files.

**Comment by vverma022** [comment]
> As of now I have just added 2 components. A button and a dropdown which will act as the trigger's for the dark mode. So instead of using one of the default colour schemes implement it manually by changing and adding theme's in the index.css and tailwind files.

<img width="249" alt="Screenshot 2024-06-26 at 9 44 10 PM" src="https://github.com/aadeshkulkarni/figuringout/assets/109036913/4627f110-46a5-46f1-9d53-35f18dbe6dab">

**Comment by vverma022** [comment]
Revising the date of completion I might take a bit more than a day. But it'll be done before this week

**Comment by aadeshkulkarni** [comment]
Thank you for your contribution @vverma022 !!
