### ISSUE TITLE
🚀 Super Feature | Implement  QnA

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#154]
### Whaaaat ?
- A user should be able to post a question. (with an optional description & with an option to be anonymous if needed)
- A user should be able to answer any question. (1 question can have many answers)
- A user should be able view all questions that are posted as a list.
- A user should be able to view a particular question and all it's answers.

### Reference apps:
- Quora
- Stackoverflow
- Reddit
- Fishbowl

#### Architecture:
- Design DB Schema 
- Design API routes 

#### Development:
- Develop API routes

Optional & Bonus:
> Users should be able to upvote question & answers.

**Comment by QQ07** [comment]
so there should be the following routes..

- [ ] POST /add-question 
       body: question, description
- [ ] GET /questions (user feed)
- [ ] POST /add-answer
       body: question-id, answer
- [ ] GET /question/:id
       to get all answers of a question.

from top level, these are the required APIs right?

**Comment by aadeshkulkarni** [comment]
That is correct.

**Comment by shubbhhh** [comment]
For DB schema should we use existing tables?
For features like; 
Answer -- comments can be used
Upvotes -- claps
Tags

Or should just make new schemas?

**Comment by aadeshkulkarni** [comment]
We can do it. But for separation of concerns, lets keep them different.  We don't want to the other feature to break if something breaks in this feature.
