### ISSUE TITLE
Bug | Scroll position on Blogs

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#156]
### Where ?

The transition between blogs > blog/:id > Back to blogs page.

### What ?

- User is scrolling through the blogs list.
- User click on a particular blog (let's say after scrolling 2 times)
- User reads the blog and clicks on the back button
- User should be redirected to the exact position they were before. (2 times scrolled position)

When a user goes back, instead of making a new API call to backend, the app should cache the previous API responses and use them.

**Comment by Jaishree2310** [comment]
I can try this issue too.

**Comment by aadeshkulkarni** [comment]
Please share your approach
