### ISSUE TITLE
🔥 Generative AI | Build Jarvis to assist in content creation

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#161]
### Context:

The app needs content. *Quality content*. The users write content. But, we don't have enough users. 

No Users => No content.
No content => No Users.

We are in a dilemma. Should we increase users or should we add a lot of blogs ? This is the Chicken-Egg problem that we want to solve in this ticket.

Although there might be different ways to solve this problem, here is 1 way to solve this.

- Decide on a niche topic - Let's say Movie reviews or Latest Tech reviews or Spirituality or Romance or Wealth.
- Pick a youtube channel that provides some really nice insights on that niche topic.
- Now, the main task. Create a simple Jarvis.js Javascript program that does the following:
1. picks youtube videos from the channel, (you can use youtube api for this)
2. sends the youtube link to Google Gemini , and asks Gemini to generate a 150-250 words Blogs with a suitable title. 
3. Stores the result in MongoDB or publishes the articles as a Bot using Puppeteer. (this is not important, can be optional. Reaching step 2 will do, if step 3. is too much trouble)

Feel free to ask questions. And Feel free to share other ways to increase blogs / users to the application. I'm all 👂🏻

**Comment by Robot-dev11** [comment]
Can i work on this?

**Comment by aadeshkulkarni** [comment]
Sure, share your development approach first.

**Comment by Robot-dev11** [comment]
The development approach for a jarvis.js program that generates blog content from Youtube DATA API and Google Gemini.

1) Libraries and Tools:
 - Javascript: We'll use Javascript for the program logic.
- Youtube Data API v3: This API allows us to access information about YouTube channels and videos.
- Google Cloud Natural Language API (optional): While Jarvis.js doesn't natively support it, we can consider integrating the Cloud Natural Language API to extract keywords or summarize video content before sending it to Gemini.

2. Development Stages

1) Authentication:

We'll need to create a project in Google Cloud Platform (GCP) and enable the Youtube Data API.
Obtain API credentials (API key) to authenticate requests to the Youtube Data API.
Fetching Youtube Videos:

Use the Youtube Data API to retrieve a list of videos from the chosen channel based on its channel ID.
We can filter the list to get only recent videos or videos with specific keywords in the title.
Extracting Video Information (Optional):

(Optional) Use the Youtube Data API to get details about each video, such as title, description, and transcript (if available).
Alternatively, consider the Cloud Natural Language API to analyze the video title and description, potentially extracting keywords or a short summary.
Sending request to Google Gemini:

Formulate a request to Google Gemini including the Youtube video URL.
Specify the desired blog content length (150-250 words) and a title generation request.
Processing Gemini Response:

Parse the response from Gemini, which should contain the generated blog content and potentially a title.
Saving the Blog Content:

Store the generated blog content (title and body) in a desired format (e.g., text file, database)

**Comment by aadeshkulkarni** [comment]
Alright, issue assigned.

**Comment by Robot-dev11** [comment]
I have an **Idea**

Can we create a cron job for it?
Cronjobs use puppeteer to automate the process of creating and copying content.
CronJob operates as a scheduler over here.

For example, we can publish content on a daily basis to provide readers with new perspectives or themes. 

References:
https://crontab.guru/

**Comment by aadeshkulkarni** [comment]
Yes, good idea.

Once the script is ready, we could eventually choose cron as the medium of execution. Let's keep that aspect out of the scope of this ticket.

**Comment by aadeshkulkarni** [comment]
@Robot-dev11 - How's it going ? Any timeline estimates with this one ?

**Comment by Robot-dev11** [comment]
Hi @aadeshkulkarni,

I have done the major changes for the content optimization.

1) Removed the YouTube APIs. The reason is the content was not generated properly. It was not giving details about the niche topic, but rather generating content of the videos like "In this video," which is not proper content to publish in the blog. So, I removed this functionality and focused on the part where a random topic is selected and we directly give it to the Gemini to create the blog.

2) I am working on the Puppeteer and I will raise the PR in the evening.

**Comment by aadeshkulkarni** [comment]
Giving a topic and generating content is already implemented. The users can do this from the write feature.

The problem with generating content with a random topic is that there is a high probability no one will read it. Because of the relevance of the content. 
The reason we were planning to go with Youtube was so that the content is relevant to what's happening around the world. 
If not youtube, we would need to figure out some other way to stay relevant. Because without relevance, the app will have just spammed blogs. People should really enjoy reading the blogs. It should add quality to their life.

Instead of puppeteer, can you seed the data directly into the database via the script ?
The reason for this is we will be moving from traditional login to Google Auth soon. And puppeteer might break then.

**Comment by Robot-dev11** [comment]
Hi @aadeshkulkarni,

I got your point and understand the importance of relevance in the content. I will remove the Puppeteer implementation. 

I'll also work on finding another method to ensure the content is relevant and engaging for the users.

I will provide some estimations soon.

**Comment by aadeshkulkarni** [comment]
Closing due to slateness and lack of relevance.
