### ISSUE TITLE
Feature | Recommend blogs 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#178]
### Where ?
- User is reading a blog.
- User scrolls until the end of the blog.

### What ?
- User get's 3-4 recommended blogs to read next
- The blogs could be related to the topics
- The blogs could be related to the author

### Implementation
- Add a new route for recommendation in the backend GET /blog/recommendation/:blogId that returns a list of 3-4 blogs.
- Add a new component to the bottom of the blog page that renders the recommended articles as cards.

### Things to note
- Not all blogs have topics assigned to them.
- Not all Users have more than 1 blog written.
- In cases where topics and author blogs are unavailable, the API should return the most recent blogs.

- This ticket requires you to work on frontend and backend. 
- Responsiveness is necessary.

**Comment by codeseker** [comment]
I am working on this feature

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Is this issue still available? If yes, can you assign it to me?

Also, I was going through the code we need for this feature. I suggest creating a new component for article image generation since it will be used in two places for now.

**Comment by aadeshkulkarni** [comment]
Sounds good. Let's do it. Issue assigned.

**Comment by aadeshkulkarni** [comment]
I think, there is a blogs/recommended API for home page, you can make adjustments in that, if required. but please ensure nothing breaks.
