### ISSUE TITLE
Enhancement | Publish Flow

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#179]
### Current Scenario:

- User signs in / signs up
- User clicks on write button
- User add blog title and content
- **User clicks on publish button (The blog is published)**
- User selects topics from the dropdown
- **User clicks on the publish button to link topics to blog.**

### Expected Scenario:

- User signs in / signs up
- User clicks on write button
- User add blog title and content
- **User clicks on publish button (The blog shouldn't publish at this moment)**
- User selects topics from the dropdown
- **User clicks on the publish button to link topics to blog. (The blog should get published and the topics should get assigned here)**

### Note:
- While inserting to post and topics schema, use Transactions to ensure Atomicity & Consistency in the backend.

**Comment by vverma022** [comment]
So the user needs to be automatically be routed to the different routes in the fronted bit of the project ?

**Comment by aadeshkulkarni** [comment]
> So the user needs to be automatically be routed to the different routes in the fronted bit of the project ?

No
