### ISSUE TITLE
Bug | Bookmark 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#181]
### Where ?

- User signs in
- User opens up a blog
- User clicks on the bookmark icon

### What ?
3 issues
- When user clicks on bookmark icon, A loader shows up. It causes layout shift. This is not required. The loader should be removed.
- The bookmark icon should turn dark once the button onClickHandler completes a successful execution. It stays the same color at the moment.
- If a user has bookmarked a blog, it should be already dark to indicate that user has bookmarked it previously.

### Screenshot

https://github.com/aadeshkulkarni/medium-app/assets/67855887/de24756c-270a-4a9b-93d9-3b65bfa19bc4

**Comment by Kunall-singh** [comment]
can i work on this issue?

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by Kunall-singh** [comment]
@aadeshkulkarni , I need your help with this. I'm trying to find the loophole that is causing this problem.

First of all, I needed to create another endpoint in the backend to check if a page is bookmarked or not. Previously, we only had a GET route that fetched all bookmarked posts but did not check each one separately. To check if a blog is bookmarked, I created a new route that takes a blogId to check if there is any bookmark associated with it.

So far, I have determined that when I unbookmark a blog, a DELETE request is sent to the backend, which also deletes a bookmark with a certain bookmarkId. However, after reloading the page, it still shows as bookmarked. I know this might be a very small code issue, but I haven't been able to figure it out. Do you have any idea how to solve this? you can check my most recent commit for code reference. 

https://github.com/aadeshkulkarni/figuringout/assets/107796595/6aaab2e7-e9d1-4ec7-abab-297c02df8787

**Comment by aadeshkulkarni** [comment]
There is no need to create one more endpoint. 

The `api/v1/blog/:blogId`returns bookmarks. 
Just checking if the bookmarks array contains loggedin user's id should suffice.

See screenshot attached

![Screenshot 2024-06-26 at 9 03 18 PM](https://github.com/aadeshkulkarni/figuringout/assets/67855887/a58d7470-fb27-41bd-98b5-d0bb5bee013c)

**Comment by Kunall-singh** [comment]
@aadeshkulkarni Thank you! That screenshot helped a lot. Previously, the bookmarkId was defined, but it was expected from the bookmarks array, causing the delete function not to work. I should have checked the network tab earlier to find this issue. Anyway, thank you very much!
