### ISSUE TITLE
Bug | Delete blog

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#182]
### Where ?

- User signs in
- User creates a blog
- User tried to delete the blog

### What ?
- A confirmation dialog should appear to confirm that user really wants to delete the blog.

### Screenshot:

![Screenshot 2024-06-15 at 8 35 49 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/c4c5aada-cdce-4288-9dd9-26db20dc78f8)

**Comment by Kunall-singh** [comment]
Please assign this issue to me. For the dialog box positioning, I suggest placing it in the middle of the screen. This way, it's easier for users to click on it directly without having to scroll to the top. Please share your thoughts.

**Comment by aadeshkulkarni** [comment]
Alright. Assigning it to you.
