### ISSUE TITLE
Bug | Search for Tags

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#185]
### Where ?
- User clicks on search
- User types a tag name (for example, 'spirituality')

### What ?
- At the moment, nothing happens
- Ideally, the app should navigate to /blogs?tag=[tagId]

### Screenshot:

![Screenshot 2024-06-15 at 8 45 05 PM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/fa8a8482-6f02-4342-9ed4-648257e1bb80)

**Comment by ivan2214** [comment]
Is anyone working on this?

**Comment by aadeshkulkarni** [comment]
Not yet

**Comment by preritagrawal06** [comment]
Hey!
If no one is assigned to this issue I can work on it. Can you assign me this issue?

**Comment by aadeshkulkarni** [comment]
Sure, assigned it to you.
