### ISSUE TITLE
Bug | Mobile screen | Scroll snap 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#189]
### Where ?
Mobile screen only
- home page
- /blogs page

### What ?
- User scrolls down from 1 blog to another.
- The scroll should snap from 1 blog to another in a smooth transition.

### Additional info
- The scroll snap was working fine a couple of days. Recent changes have mostly caused the error.

**Comment by pramitxray** [comment]
Please assign this to me.

**Comment by aadeshkulkarni** [comment]
Sure
