### ISSUE TITLE
Workflow | PR template

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#190]
# When ?
- Developer creates a Pull Request.

# What ?
- Developer should be given default PR template which includes checklist.

# Reference
- [Use Github ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

<hr />

### Example template

Resolves #[Issue Number if there]

Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

**Comment by iam-abhishek-yadav** [comment]
Hi, we can create a simple file like this


## Description



Resolves #[Issue Number]

## Changes



- Change 1
- Change 2
- ...

## Screenshots/Recordings



## Checklist

Please ensure the following before requesting a review:

- [ ] I have performed a self-review of my code
- [ ] I assure there are no similar/duplicate pull requests regarding the same issue
- [ ] My changes follow the project's coding guidelines and best practices
- [ ] Code is formatted properly and lint check passes successfully

## Additional Notes

**Comment by aadeshkulkarni** [comment]
Sounds good. Can you work on this ?

**Comment by iam-abhishek-yadav** [comment]
Sure, do I need to get this assigned?

**Comment by aadeshkulkarni** [comment]
Thank you for your contribution!
