### ISSUE TITLE
Bug | Blogcard | Topics click

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#195]
### Where ?
- User visits the landing page or /blogs
- User clicks on the topic from any blog card

### What ?
- The app should navigate to /blogs?tagId=[tag] instead of navigating to /blog/:blogid

### Screenshot:
> Finance tag 
<img width="1783" alt="Screenshot 2024-06-20 at 7 03 04 PM" src="https://github.com/aadeshkulkarni/figuringout/assets/67855887/d219f238-469d-4ab2-9f46-329f2496522b">

**Comment by Chandan9898Kumar** [comment]
If you could get the video of issue and expected behaviour.

**Comment by krishchvn** [comment]
Hey. I want to work on this issue. This will be my first contribution. Can you assign it to me?

**Comment by aadeshkulkarni** [comment]
Sure, make sure you go through contributing.md doc before starting dev. All the best!

**Comment by krishchvn** [comment]
Hi Aadesh,
I'm trying to setup Prisma, I've generated and added API keys from Aiven and Prisma in .env file and Prisma API key in wrangler.toml file.
While running npm run deploy, I'm facing below error
![image](https://github.com/aadeshkulkarni/figuringout/assets/58606754/8443e60a-2cb1-45b1-b470-74f1d3e03965)

I've also logged in on wrangler and installed accelerate as per Commands.md.
Can you help me out here?

**Comment by aadeshkulkarni** [comment]
> Hi Aadesh, I'm trying to setup Prisma, I've generated and added API keys from Aiven and Prisma in .env file and Prisma API key in wrangler.toml file. While running npm run deploy, I'm facing below error ![image](https://private-user-images.githubusercontent.com/58606754/344275833-8443e60a-2cb1-45b1-b470-74f1d3e03965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDgxMjUsIm5iZiI6MTcxOTY0NzgyNSwicGF0aCI6Ii81ODYwNjc1NC8zNDQyNzU4MzMtODQ0M2U2MGEtMmNiMS00NWIxLWI0NzAtNzRmMWQzZTAzOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA3NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWY0MTJmOWRmNWVjY2IzZDc4ZWZmOThlYTg1MDI4ZGM1ZTlkMGZiMGFmODE0ZDE3NzIzNDc5ZTlkNTQzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnIg6vHstik2J_EXcQifsyS_pdLGOJzwNsoMyhvGLzY)
> 
> I've also logged in on wrangler and installed accelerate as per Commands.md. Can you help me out here?

You don't need to run the deploy command to run the app locally.

That command deploys the backend to Cloudflare. The Commands.md file can be ignored for setting up the codebase. 
Its only used by me when I need to make deployments.

**Comment by krishchvn** [comment]
Thanks, Aadesh.

![image](https://github.com/aadeshkulkarni/figuringout/assets/58606754/8b482bfd-1a31-4299-af21-d4667766b1e2)

When I click the pill ("topics"), it already has the the tagid on it ("/blogs?tagId=[tag]").
Even in the codebase, tagid is attached already. 
![image](https://github.com/aadeshkulkarni/figuringout/assets/58606754/9e213bd1-f0a1-44ad-92a0-6a8101e6c8ae)

When I click on the pill, it redirects to showing all blogs/BlogCards which has Pill included in tags.  
[recording-2024-06-29-20-32-06.webm](https://github.com/aadeshkulkarni/figuringout/assets/58606754/c5767802-b17d-4054-ad49-85ad40f3b1d6)

Am I not understanding the issue here, or is it already solved?

**Comment by aadeshkulkarni** [comment]
Looks like it's already solved. Thanks for your contribution.
