### ISSUE TITLE
Enhancement | Profile page | Show blog count, bookmark count, member since

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#197]
### Where ?
- User signs in
- User goes to profile page

### What ?
- User should be able to see total count blogs they've created.
- User should be able to see total count blogs they've bookmarked.
- User should be able to see `Member since: Month, Year`

### Position ?
- Beneath Followers count

### Screenshot

<img width="1783" alt="Screenshot 2024-06-20 at 7 06 24 PM" src="https://github.com/aadeshkulkarni/figuringout/assets/67855887/450c374a-64b2-45b4-97b0-58fb315d58ae">

**Comment by shambhabya** [comment]
Can i work on this?

**Comment by dev13-suthar** [comment]
![Screenshot 2024-07-02 085927](https://github.com/aadeshkulkarni/figuringout/assets/83634894/61ed6c40-872b-4ec3-95aa-e8a408c6dd7c)

something like this,
i have set up the backend for this just need hints about FE

**Comment by aadeshkulkarni** [comment]
> ![Screenshot 2024-07-02 085927](https://private-user-images.githubusercontent.com/83634894/344866413-61ed6c40-872b-4ec3-95aa-e8a408c6dd7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjEwMDIsIm5iZiI6MTcyMDAyMDcwMiwicGF0aCI6Ii84MzYzNDg5NC8zNDQ4NjY0MTMtNjFlZDZjNDAtODcyYi00ZWMzLTk1YWEtZThhNDA4YzZkZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE1MzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NTU3ZGIyMmY0OTQ4ZjVhZTkwN2U1MDZlNjY2MTk5NmNmYTAxMzRiYTVmN2ZhYjY5MTg4OTdlZTAwNDhiZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6qUyn9arKNZ9SNqo4Y20QxFSj2SAEJYB-x8AUPr7PPA)
> 
> something like this, i have set up the backend for this just need hints about FE


Please get the issue assigned first before starting development.

**Comment by aadeshkulkarni** [comment]
> Can i work on this?

Sure, assigned to you.

**Comment by dev13-suthar** [comment]
@shambhabya you working on this?

**Comment by shambhabya** [comment]
> @shambhabya you working on this?

I will start working on it from today

**Comment by shambhabya** [comment]
I can't work on this right now @aadeshkulkarni , you can assign it to @dev13-suthar

**Comment by dev13-suthar** [comment]
sure i can work on this

**Comment by aadeshkulkarni** [comment]
Sure, assigned it to you.
