### ISSUE TITLE
Enhancement | Recommended topics | Backend

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#201]
- Create a new backend route for recommended topics
- GET tags/recommended 
- return top 5 tags with maximum posts.

**Comment by shubbhhh** [comment]
This can be implemented by:
performing group-by on tagsOnPost table, grouping by tagId and
ordering them in decreasing order by count of postId and selecting only top five tagIds

**Comment by aadeshkulkarni** [comment]
Sure, assigned it to you
