### ISSUE TITLE
Enhancement | Recommended subscribers | Backend

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#202]
Create a new backend route for recommended subscribers
GET subscriber/recommended
return top 5 tags with maximum followers.

**Comment by shubbhhh** [comment]
If recommended user are shown on frontend on explore page(blogs) even to unauthenticated users then this(GET subscriber/recommended) route should be above auth route in subscriberRouter.
We can fetch most subscribed user from subscriber table by grouping by userId and ordering by subscriberId count.

can I work on issue?

**Comment by aadeshkulkarni** [comment]
Yes, it should be a public route. 
Have already assigned #203 to you. 
If (you complete that issue AND no one else claims this one until that time) then, this will get assigned to you.

**Comment by shubbhhh** [comment]
Should I start working on this issue now?

**Comment by aadeshkulkarni** [comment]
Yes sir.
