### ISSUE TITLE
CORS error when trying to Sign Up

### ISSUE THREAD

**Issue by rajeev1202** [aadeshkulkarni/figuringout#206]
I tried signup on website [figuringout/signup](https://www.figuringout.life/signup) from brave browser, on filling details upon clicking Sign Up button there is no routing or successful sign up message. Looked into dev tools and saw CORS error.
Attaching ss for reference.
![image](https://github.com/aadeshkulkarni/figuringout/assets/29862832/2bfb7b3e-c951-482c-982d-0ac8f76ebfaf)

**Comment by aadeshkulkarni** [comment]
Unfortunately, I don't have Brave browser on my system. Can someone else please confirm this issue on Brave please?

**Comment by Prathamesh0901** [comment]
No issue. Worked for me.

**Comment by ramnaresh8** [comment]
I tried it on Brave but its working fine for me
