### ISSUE TITLE
Feature | Implement Recoil for State management | Blogslist

### ISSUE THREAD

**Issue by dev13-suthar** [aadeshkulkarni/figuringout#210]
When a user clicks on post for reading whole post it fetches  data  from backend  after going back  and  user  clicks on same post again it sends another  backend call, instead it is good idea to store this single post in Atoms,so it does not refetches the post.

**Comment by aadeshkulkarni** [comment]
Good idea. We would need to setup Recoil to the project first.

**Comment by dev13-suthar** [comment]
yes working on it
