### ISSUE TITLE
Long post titles get cut-off

### ISSUE THREAD

**Issue by debopriyobasu** [aadeshkulkarni/figuringout#215]
**Where is the issue?**
When the user clicks on the story and the story opens, the title is cut-off. 
Here is a a screenshot: 
<img width="1264" alt="Screenshot 2024-06-26 at 9 12 45 PM" src="https://github.com/aadeshkulkarni/figuringout/assets/108874674/f90353c0-394d-4b05-b07a-46ce9670d068">

**Possible solutions:**

1. We can either remove the line-clamp-4 class to remove the limit, as ideally, when the user opens a story, the entire title should be displayed, or the user misses the context.
2. A better solution would be to limit the user to create post titles up to a specific character limit. 

I am open to discussion regarding any better solution to this.

**Comment by aadeshkulkarni** [comment]
Let's go with option 2, limiting the character count.

Would you like to pick this for dev ?

**Comment by debopriyobasu** [comment]
> Let's go with option 2, limiting the character count.
> 
> Would you like to pick this for dev ?

Yes, sure!

**Comment by aadeshkulkarni** [comment]
Assigned it to you, @debopriyobasu 

Please go through the contributing.md once before starting dev.
