### ISSUE TITLE
Configuration | 1 command to run 'em all

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#219]
### Current scenario

At the moment, a developer needs to run 2 commands to spin up the app locally
```bash
cd frontend && npm run dev
cd backend && npm run dev
```

### Expected Scenario

Run `npm run dev` from project root. 
This command should run the above commands behind the scenes.

We want to make developer experience smoother so that first time contributors  can setup the projects quickly.

**Comment by abidta** [comment]
Hi @aadeshkulkarni , I'd like to work on this issue.

**Comment by abidta** [comment]
Hi @aadeshkulkarni , I'd like to work on this issue.
Here's my plan:

1. I will create a `dev` script in the root `package.json` that uses `concurrently` to run both frontend and backend development servers simultaneously.
2. I will ensure that `concurrently` is added as a dev dependency in the root `package.json`.

Here's how the root `package.json` will look:

```json
{
  "scripts": {
   "dev": "concurrently --prefix \"[{name}]\" --names \"frontend,backend\" \"cd frontend&& npm run dev \" \"cd backend && npm run dev\" "
  },
  "devDependencies": {
    "concurrently": "^8.0.0"
  }
}

**Comment by aadeshkulkarni** [comment]
Sounds good. Assigned the issue to you.

**Comment by aadeshkulkarni** [comment]
Please make sure you update the readme accordingly.
