### ISSUE TITLE
Enhancement | Recommended subscribers (FE)

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#220]
### Where ?
- User visits home page

### What ?
- User should be able to see recommended subscribers.

### Screenshot
<img width="1788" alt="Screenshot 2024-06-27 at 10 38 38 AM" src="https://github.com/aadeshkulkarni/figuringout/assets/67855887/a63312ed-93a9-49a3-8f3e-37f33faa9d08">

### Note

- The backend route to fetch recommended subscribers is available at GET `/subscriber/recommended`
- It will always return maximum 5 user profiles.
- The card should list the user profiles as list items. (Please refer medium's designs for reference)
- The entire layout should be responsive. 

We are at a critical point in development where the pages will become data intensive. 
In your own capacity, please be mindful that we are not degrading the UX or the performance of the application. Be conscious.

**Comment by aadeshkulkarni** [comment]
Sure, assigned to you

**Comment by aadeshkulkarni** [comment]
@malisettisamrat - Any update on this ?

**Comment by malisettisamrat** [comment]
@aadeshkulkarni , working on it. Will raise a PR soon. Thanks !

**Comment by malisettisamrat** [comment]
<img width="1377" alt="Screenshot 2024-07-13 at 2 06 13 AM" src="https://github.com/user-attachments/assets/dd4b5e99-5212-4755-9bc1-941693fe949c">


@aadeshkulkarni, Do you mean the subscribers are the list of people to follow mentioned in the above screenshot?

**Comment by aadeshkulkarni** [comment]
> <img alt="Screenshot 2024-07-13 at 2 06 13 AM" width="1377" src="https://private-user-images.githubusercontent.com/44539602/348461756-dd4b5e99-5212-4755-9bc1-941693fe949c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4Njc0NTMsIm5iZiI6MTcyMDg2NzE1MywicGF0aCI6Ii80NDUzOTYwMi8zNDg0NjE3NTYtZGQ0YjVlOTktNTIxMi00NzU1LTliYzEtOTQxNjkzZmU5NDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEwMzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNGI5ODdiOWQ1MDM0YjIzM2VhNjZhYzc1NTc0OTUwNTczMzc4ZjgyMzZmMGZjZWJkMTQwMTU0ZGEzMGM1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w8_l-d4ysNOPpTYlEXQ5vMdSQrfhFosLtmhblH7k0T4">
> @aadeshkulkarni, Do you mean the subscribers are the list of people to follow mentioned in the above screenshot?

yes.

**Comment by malisettisamrat** [comment]
Hi @aadeshkulkarni, opened a PR #255 and resolved merge conflicts. Thanks!
