### ISSUE TITLE
Bugfix | Shimmer for contributors page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#221]
### Where ? 
- /contributors

### What ?
- The shimmer loads at an incorrect position
- Also the shimmer elements should be displayed according to the current layout. It's currently displaying an old style.

### Screenshot

![Screenshot 2024-06-27 at 4 20 18 PM](https://github.com/aadeshkulkarni/figuringout/assets/67855887/6165bb24-7b65-46b7-adb8-dc73e92eb7ac)
![Screenshot 2024-06-27 at 4 19 52 PM](https://github.com/aadeshkulkarni/figuringout/assets/67855887/0654a8f5-a3fc-467e-a27a-f6999404ceb3)

**Comment by malla-lokesh** [comment]
Hi @aadeshkulkarni, I would like to work on this issue

1. For displaying the shimmer elements same as actual contributor list. I'd just add the similar width to the shimmer list.
2. While loading, should the shimmer UI contain the ContributionNotification also?

Also I found some bugs around contributor name wrapping incorrectly for medium size.

![image](https://github.com/aadeshkulkarni/figuringout/assets/121516538/83692d5b-d5a8-4fee-a764-387167dfee84)

Shall I open a new issue for it?

**Comment by aadeshkulkarni** [comment]
Sounds good. 

No, the notification is rendered quickly. There is no need to add shimmer there.
