### ISSUE TITLE
Bug | Blog Title should wrap itself before crashing with the blog image.

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#232]
### Screenshot

![Screenshot 2024-07-03 at 9 06 44 PM](https://github.com/aadeshkulkarni/figuringout/assets/67855887/cb786342-ecbe-4518-912f-c933e37e1dd7)

**Comment by Shashan17J** [comment]
@aadeshkulkarni please review.

**Comment by aadeshkulkarni** [comment]
Thank you for your contribution!
