### ISSUE TITLE
Feature | Stats page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#233]
Stats page

### Backend:

new statsRouter

- Total users count
- Total blogs count
- Total contributors count
- Top 5 users by subscriber count
- Top 5 blogs by claps count
- Top 5 tags by blogs count

### Frontend

new /stats page

Minimalistic ui, be creative if needed, not mandatory. Just display these stats as list / cards.

**Comment by nipunh** [comment]
I will get started on this feature

**Comment by aadeshkulkarni** [comment]
@nipunh - What's the update on this one ?

**Comment by nipunh** [comment]
Will complete over the weeken

**Comment by nipunh** [comment]
> Will complete over the weekend
Can you give me access to the repo, I have forked it for now and working on it
