### ISSUE TITLE
Bug | Topics with 0 posts

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#241]
### Current:
All topics are displayed at the top. Even topics with 0 posts.

### Expectation:
- Show only those topics which have at least 1 post.
- Sort topics by count(posts)

### Note:
- Implement this in the backend

**Comment by AbdulWahab3181** [comment]
Hi @aadeshkulkarni ! I would like to work on this. Could you please explain a little more as I am new here? Also, could you please tell me if there is a bounty? If yes, what's the amount and what is the process?

**Comment by 0xprathamesh** [comment]
Hi @aadeshkulkarni ,
I would like to work on the enhancement to display only those topics which have at least 1 post and to sort topics by the count of posts. Could you please assign this task to me? and i would also like to add a `Saved Posts` page so that the user can see his saved post.

**Comment by aadeshkulkarni** [comment]
> Hi @aadeshkulkarni , I would like to work on the enhancement to display only those topics which have at least 1 post and to sort topics by the count of posts. Could you please assign this task to me? and i would also like to add a `Saved Posts` page so that the user can see his saved post.

Assigning this issue to you.
Saved post page is not required. We already have a bookmarks page that achieves this.

**Comment by vverma022** [comment]
Could I work on this

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by vverma022** [comment]
Thank you I'll create an approach to the problem and post my solution after looking at the codebase.

**Comment by vverma022** [comment]
@aadeshkulkarni will filtering the blogs in the prisma query a right approach to the bug. I could modify the blogRouter.get("/bulkUser/:id", async (c) => {} api. Are there any other backend end-points I need to take into consideration.

**Comment by vverma022** [comment]
> @aadeshkulkarni will filtering the blogs in the prisma query a right approach to the bug. I could modify the blogRouter.get("/bulkUser/:id", async (c) => {} api. Are there any other backend end-points I need to take into consideration.

Like the tag route as well.

**Comment by aadeshk-beam** [comment]
> @aadeshkulkarni will filtering the blogs in the prisma query a right approach to the bug. I could modify the tagRouter.get("/", async (c) => { try { const prisma = getDBInstance(c);
> 
> ```
> 	let query: any = {
> 		select: {
> 			id: true,
> 			tagName: true,
> 		},
> 	};. 
> ```
> 
> Are there any other backend end-points I need to take into consideration.

Yes, that's the right approach. 
Implementation-wise, 
tagRouter.get("/") -> should return all tags.
You can extend this route by adding query param `?active=true` which can return topics with the this ticket's conditions.

**Comment by aadeshkulkarni** [comment]
@vverma022 - Your code breaks. Did you not verify your code by running it locally ?

**Comment by vverma022** [comment]
> 
> 
> <img width="1796" alt="Screenshot 2024-07-24 at 10 11 58 AM" src="https://github.com/user-attachments/assets/15199f8c-bb63-4d9b-9a6e-6959e9f08ea3">
> 
> 
> 
> @vverma022 - Your code breaks. Did you not verify your code by running it locally ?
> 
> 
> 
> Reverting your changes so that app is functional

Apologies for the oversight. I have some issues in my backend setup. Un-assigning

**Comment by vverma022** [comment]
While filtering the tag router a bug is that an even while publishing a blog when selecting a tag the other do not show-up. So in the Tags.tsx compontent a filter will be needed.
