### ISSUE TITLE
Users are able to react to a post by clicking on the clap icon as many times as they want.

### ISSUE THREAD

**Issue by ganeshdanuri** [aadeshkulkarni/figuringout#243]
steps to reproduce 

1. open on any post to read 
2. click on the clap icon

Refer the video below : 
https://github.com/aadeshkulkarni/figuringout/assets/83338453/6a5b1275-91cd-4b64-912b-31784bd2f9aa

**Comment by aadeshkulkarni** [comment]
That's an intended feature. 
Users can clap maximum 10 times per post. 
The number of claps determines how much they appreciate the post.
