### ISSUE TITLE
Bug | UI | Bookmarks page | Bg 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#246]
- Make background transparent for bookmark container. (like blogs)
- Light & Dark mode both

### Screenshot:

![Screenshot 2024-07-12 at 10 19 14 PM](https://github.com/user-attachments/assets/56dbac91-7cd5-4b8f-9d49-34b04190aa44)

**Comment by vverma022** [comment]
I'd like to work on this.
