### ISSUE TITLE
Enhancement | UI | Profile page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#247]
### Where ?
- User signs in
- User goes to Profile page (from top right)
- User goes to About tab

### What ?
- Replace existing inputs, buttons with Shadcn components.
- Change border color of Input elements to darker shade of gray for dark mode.
- Change text color of hint text to light shade of gray so that it's readable for dark mode.

### Screenshot
![Screenshot 2024-07-12 at 10 22 25 PM](https://github.com/user-attachments/assets/c2aa1e89-2d1c-4d91-90e7-014c66c8b059)

**Comment by malla-lokesh** [comment]
Hi @aadeshkulkarni , Can you assign this issue to me?

**Comment by nipunh** [comment]
I can take this one nwxr
