### ISSUE TITLE
Bounty 6$ | Feature | Thought

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#249]
### What ?
- At the moment, users can write blogs. Blogs are long form content. 
- Introducing Thoughts. User can write a thought. Thoughts are short form. Think of 1 Thought like a Twitter post or Threads post. 

### How ?

1. backend/prisma/schema.prisma - 

```javascript
model Thought {
  id            String     @id @default(uuid())
  content       String
  publishedDate DateTime   @default(now())
  published     Boolean    @default(false)
  author        User       @relation(fields: [authorId], references: [id], onDelete: Cascade)
  authorId      String
}
```
Run prisma migrations to update db with schema

2. backend/src/routes/thought.ts - thoughtRouter
```bash
thoughtRouter.post
thoughtRouter.put
thoughtRouter.get: 1 and all
thoughtRouter.delete
```
create, update, delete - protected routes
get - public routes

3. Test all routes on Postman (optional)

<hr />

4. frontend/src/pages/Thought.ts - 
```bash
1. Create Thought button 
2. Show all Thoughts
3. Delete Thought 
4. Update Thought
```

The frontend should be simple, page/Thought.ts is a temporary placeholder to test the backend setup. We will eventually integrate it into the App.

**Comment by pheonix-coder** [comment]
Bounty available or claimed ?
