### ISSUE TITLE
Google OAuth Client Not Found

### ISSUE THREAD

**Issue by tiluckdave** [aadeshkulkarni/figuringout#260]
<img width="497" alt="image" src="https://github.com/user-attachments/assets/1e296685-19fb-4805-9088-ca3dd2af1684">

### Steps to reproduce

Signup a new account using Google Provider.

**Comment by nipunh** [comment]
@tiluckdave Can i take this one?

**Comment by tiluckdave** [comment]
> @tiluckdave Can i take this one?

I am not a maintainer here.
