### ISSUE TITLE
AI questions are confused as comments

### ISSUE THREAD

**Issue by tiluckdave** [aadeshkulkarni/figuringout#263]
<img width="828" alt="image" src="https://github.com/user-attachments/assets/ffb71814-03b9-4e15-8b7f-968643510acd">

Placement of asking AI questions makes it look like that is comments on the website. Making the feature less used. Comments can be added at that place and chat option could be provided as a floating box on the bottom right.

**Comment by nipunh** [comment]
@tiluckdave Can you assign this to me?

**Comment by aadeshkulkarni** [comment]
@tiluckdave - you're right.
