### ISSUE TITLE
Feature | Implement Social Share Preview for a blog link

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#53]
### Expectation:
When a user wants to share an article on their socials, the app should show a beautiful thumbnail / preview.

The preview should work everywhere, and but minimum following socials should be checked:
- Whatsapp 
- Instagram
- LinkedIn
- Facebook
- X (Twitter)

The preview should have 
- Article title, 
- Article content (clipped upto x words), 
- Article thumbnail if article image is present, else default app placeholder image

This is good ticket for someone who wants to dip their feet into SEO and social media marketing.
Refer this for implementation https://ogp.me/

Share screenshot of the end-result in the PR description.

**Comment by t007rushi** [comment]
@aadeshkulkarni assign it to me

**Comment by aadeshkulkarni** [comment]
Sure

**Comment by t007rushi** [comment]
@aadeshkulkarni 
PR added [pull/63](https://github.com/aadeshkulkarni/medium-app/pull/63)
![kung-fu-panda-review](https://github.com/aadeshkulkarni/medium-app/assets/61598260/09abe6ca-7a77-44c1-bed8-290a9145aa5e)

**Comment by aadeshkulkarni** [comment]
Need someone to try this approach: https://blog.logrocket.com/adding-dynamic-meta-tags-react-app-without-ssr/

**Comment by aadeshkulkarni** [comment]
Part 1 | Basic Meta tags has been implemented to the app.

Part 2 | Blog specific Meta title, description & image seems a bit complicated and might require R&D.
