### ISSUE TITLE
Feature | Ability to add a cover image to an article

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#7]
When? 
- User writes a new article.
- User edits an existing article.

What?
- User should be able to add a cover image to the article.

Challenge:
- How to persist images in the backend ?

**Comment by aadeshkulkarni** [comment]
Sure, please discuss your approach here before starting dev

**Comment by aadeshkulkarni** [comment]
@RahulSingh9131 - This has been assigned to you. Would be grateful if could estimate the timeline for this one and share it.

**Comment by RahulSingh9131** [comment]
i saw this now , sure i will share my approach and tell the timeline for completing it.

**Comment by techypants** [comment]
A fixed w:h ratio with object cover property. Image drap and deop or select and stored in cloudinary or aws s3, generated link is got and rendered.

**Comment by RahulSingh9131** [comment]
@techypants did you already fixed this issue?

**Comment by techypants** [comment]
no not yet, suggested a method

**Comment by RahulSingh9131** [comment]
ok thanks, i will try this

**Comment by RahulSingh9131** [comment]
@aadeshkulkarni  hey i went ahead and added cloudinary for the image upload feature, and also added coverImage field in the Post collection ,after running migartion command for the prisma i am getting this error on terminal, do i need to add DATABASE_URL in .env.example file to solve this issue?

<img width="1440" alt="Screenshot 2024-05-20 at 10 52 35 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/87935709/21ceb271-14bd-44f6-ac55-3ea9abf0c14f">

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni hey i went ahead and added cloudinary for the image upload feature, and also added coverImage field in the Post collection ,after running migartion command for the prisma i am getting this error on terminal, do i need to add DATABASE_URL in .env.example file to solve this issue?
> 
> <img alt="Screenshot 2024-05-20 at 10 52 35 AM" width="1440" src="https://private-user-images.githubusercontent.com/87935709/331952100-21ceb271-14bd-44f6-ac55-3ea9abf0c14f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODYzMTUsIm5iZiI6MTcxNjE4NjAxNSwicGF0aCI6Ii84NzkzNTcwOS8zMzE5NTIxMDAtMjFjZWIyNzEtMTRiZC00NGY2LWFjNTUtM2VhOWFiZjBjMTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNWE3MWEyMDVmODBhOGVhOGU0ZWQ5ZTI4OWIwYTEwOGE2N2JjYjJlYzlhYWNmMmQzM2U5NzA4ZmQ2ZTVjZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hGKDhGADSodyxsFnRYgUw0bDsB_MsocZU53sh8-GIlA">

Yes.

You would need to create 2 things to use prisma/backend in your local system correctly:
1. Prisma connection string, (you can get one easily from aiven.io, which will be stored in .env as DATABASE_URL)
2. Prisma connection pool connection string.  ( you can get one easily from https://www.prisma.io/data-platform/accelerate , which will be stored in wrangler.toml file's DATABASE_URL

Also make sure your ./frontend/src/config.ts's BACKEND_URL is pointing to `http://localhost:8787`

**Comment by RahulSingh9131** [comment]
@aadeshkulkarni i have added the DATABASE_URL from aiven.io and also update wrangler.toml file with prisma connection string, but still i am getting erros on console while trying to run prima migrate cmd. i am getting confused in enabling this.

<img width="1440" alt="Screenshot 2024-05-22 at 10 05 12 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/87935709/3a14970c-07bf-4b29-985b-b2558c6b0a23">

**Comment by aadeshkulkarni** [comment]
@RahulSingh9131 -  You are editing **.env.example** file, instead of **.env**. 

The .env file needs to be created using .env.example as reference point.

**Comment by aadeshkulkarni** [comment]
@RahulSingh9131  - Any update on this ?

[Contributing doc](https://github.com/aadeshkulkarni/medium-app/blob/master/CONTRIBUTING.md)
