### ISSUE TITLE
Feature | Google Signup

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#8]
Users should be able to use the app using Google SSO effortlessly.

**Comment by rahul-mahato29** [comment]
Checking this, and the issue is also with {lable} - it is not reflecting , may be because dark mode is not configured.
<img width="585" alt="image" src="https://github.com/aadeshkulkarni/medium-app/assets/88178967/6c846512-a666-4f78-999c-46480efb5df9">

**Comment by aadeshkulkarni** [comment]
@rahul-mahato29 - Thank you. I've now created a new issue for the dark mode [here](https://github.com/aadeshkulkarni/medium-app/issues/9)

If you plan to pick it up, please fork the repo, create a feature branch and raise the PR and link the new issue in the PR.

**Comment by Ashutoshpadhi629** [comment]
@aadeshkulkarni can you assign me this Issue?

**Comment by aadeshkulkarni** [comment]
Sure, assigned!
